### PR TITLE
Add 3.4.0 to supported versions

### PR DESCRIPTION
**Pull request by crowity**
add 3.4.0 to supported versions

## Description
Added 3.4.0 to supported versions

## Type of changes

- [ ] Bug fix
- [ ] New feature
- [x ] Enhancement
- [ ] Documentation

### CODE REVIEW

**Comment by Sycamore0** [comment]
Cmdids where?
97ZFR5E3)0L}}MNS9LFF_M5

**Comment by crowity** [comment]
It's skill issue 😰

**Comment by Sycamore0** [comment]
image
@~2%}GYV`@%0SBP61U{STC9

**Comment by Sycamore0** [comment]
I'm still trying to fix protos and this cmdids

**Comment by crowity** [comment]
Finally I added cmdids 😨

**Pull request merged**
